# Generated by Django 5.2 on 2025-04-22 16:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения привычки",
                        max_length=250,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время начала выполнения привычки",
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие",
                        max_length=250,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "nice",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Приятная или нет",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("once_a_week", "Раз в неделю"),
                            ("twice_a_week", "Два раза в неделю"),
                            ("three_a_week", "Три раза в неделю"),
                            ("four_a_week", "Четыре раза в неделю"),
                            ("five_a_week", "Пять раз в неделю"),
                            ("six_a_week", "Шесть раз в неделю"),
                            ("seven_a_week", "Каждый день"),
                        ],
                        default="once_a_week",
                        help_text="Укажите периодичность выполнения привычки",
                        max_length=30,
                        verbose_name="Периодичность выполнения привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Укажите время, необходимое "
                                  "для выполнения действия",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, verbose_name="Публичная или нет"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберете другие привычки, "
                                  "связанные с данной",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.habit",
                        verbose_name="Связанные привычки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
